### ISSUE TITLE
HUF currency minor is wrong

### ISSUE THREAD

**Issue by v-yatsenko** [castedo/isomon#2]
Hungarian Forint has no minor decimals

**Comment by castedo** [comment]
Thanks for reporting.

Today I downloaded the ISO 4217 XML data from https://www.six-group.com/en/products-services/financial-information/data-standards.html. The ISO 4217 data has not changed for the Forint. Wikipedia also confirms the ISO 4217 subunit has not changed (https://en.wikipedia.org/wiki/Hungarian_forint).

Even though in reality  there are no minor decimals in circulation since 1999, the ISO 4217 standard keeps them. I imagine it would be too disruptive to change.
